BEGIN TRANSACTION; 


CREATE TABLE "League" (
	"LeagueName"	TEXT NOT NULL COLLATE NOCASE,
	PRIMARY KEY("LeagueName")
);
CREATE TABLE "Sport" (
	"SportName"	TEXT NOT NULL COLLATE NOCASE,
	PRIMARY KEY("SportName")
);
CREATE TABLE "Team" (
	"TeamName"	TEXT NOT NULL COLLATE NOCASE,
	"Budget"	INTEGER,
	"SportName"	TEXT,
	"LeagueName"	TEXT COLLATE NOCASE,
	PRIMARY KEY("TeamName"),
	FOREIGN KEY("SportName") REFERENCES "Sport"("SportName")
		ON UPDATE CASCADE
		ON DELETE CASCADE,
	FOREIGN KEY("LeagueName") REFERENCES "League"("LeagueName")
		ON UPDATE CASCADE
		ON DELETE CASCADE
	
);

CREATE TABLE "Coach" (
	"CoachID"	INTEGER NOT NULL,
	"CoachName"	TEXT COLLATE NOCASE,
	"Salary"	INTEGER,
	"TeamName"	TEXT COLLATE NOCASE, 
	PRIMARY KEY("CoachID"), 
	FOREIGN KEY("TeamName") REFERENCES "Team"("TeamName")
		ON UPDATE CASCADE
		ON DELETE CASCADE
);

CREATE TABLE "Spectator" (
	"SpecName"	TEXT,
	"Id"	INTEGER NOT NULL,
	"SportName"	TEXT,
	FOREIGN KEY("SportName") REFERENCES "Sport"("SportName")
		ON UPDATE CASCADE
		ON DELETE CASCADE,
	PRIMARY KEY("Id")
);


CREATE TABLE "Player" (
	"PlayerID"	INTEGER NOT NULL,
	"Salary"	INTEGER,
	"PlayerName"	TEXT COLLATE NOCASE,
	"Position"	TEXT,
	"TeamName"	TEXT COLLATE NOCASE,
	"CoachID"	INTEGER,
	PRIMARY KEY("PlayerID"),
	FOREIGN KEY("TeamName") REFERENCES "Team"("TeamName")
		ON UPDATE CASCADE
		ON DELETE CASCADE,
	FOREIGN KEY("CoachID") REFERENCES "Coach"("CoachID")
		ON UPDATE CASCADE
		ON DELETE CASCADE
);
CREATE INDEX playernameIndex
ON Player(PlayerName); 

COMMIT;
